'use strict';

/* jshint -W117 */ //(remove the undefined warning)
lo30NgApp.controller('statsPlayersController',
  [
    '$scope',
    '$timeout',
    function ($scope, $timeout) {

      $scope.searchText = null;
      $scope.selectedTeam = null;
      $scope.selectedPosition = null;
      $scope.selectedLine = null;
      $scope.selectedSub = null;

      $scope.filterByTeam = function (team) {
        var existingSearch = "team:" + $scope.filterByTeamMapper($scope.selectedTeam);
        var newSearch = "team:" + $scope.filterByTeamMapper(team);

        if ($scope.selectedTeam) {
          // if selected populated, that means there was a search before...remove that first 
          $scope.removeExistingSearchFromSearch(existingSearch);
        }

        if ($scope.selectedTeam === team) {
          // if same thing was clicked again...already been remove from search...just reset vars
          $scope.selectedTeam = null;
        } else {
          // this is a new search, add to search
          $scope.prepSearchForNewSearch();
          $scope.addNewSearchToSearch(newSearch);
          $scope.selectedTeam = team;
        }

        $scope.resetSort();
      };

      $scope.filterByTeamMapper = function (team) {
        var teamMapped;
        // map filter keys from columns to object
        switch (team) {
          case "Bill Brown":
            teamMapped = "Bill Brown Auto Clinic";
            break;
          case "Hunt's Ace":
            teamMapped = "Hunt's Ace Hardware";
            break;
          case "LAB/PSI":
            teamMapped = "Liv. Auto Body/Phillips Service Ind";
            break;
          case "Zas Ent":
            teamMapped = "Zaschak Enterprises";
            break;
          case "DPKZ":
            teamMapped = "DeBrincat Padgett Kobliska Zick";
            break;
          case "Villanova":
            teamMapped = "Villanova Construction";
            break;
          case "Glover":
            teamMapped = "Jeff Glover Realtors";
            break;
          case "D&G":
            teamMapped = "D&G Heating & Cooling";
            break;
          default:
            teamMapped = team;
        }

        return teamMapped;
      };

      $scope.filterBySub = function (sub) {
        var existingSearch = "sub:" + $scope.filterBySubMapper($scope.selectedSub);
        var newSearch = "sub:" + $scope.filterBySubMapper(sub);

        if ($scope.selectedSub) {
          // if selected populated, that means there was a search before...remove that first 
          $scope.removeExistingSearchFromSearch(existingSearch);
        }

        if ($scope.selectedSub === sub) {
          // if same thing was clicked again...already been remove from search...just reset vars
          $scope.selectedSub = null;
        } else {
          // this is a new search, add to search
          $scope.prepSearchForNewSearch();
          $scope.addNewSearchToSearch(newSearch);
          $scope.selectedSub = sub;
        }

        $scope.resetSort();
      };

      $scope.filterBySubMapper = function (sub) {
        var subMapped;
        // map filter keys from columns to object
        switch (sub) {
          case "With":
            subMapped = "Y";
            break;
          case "Without":
            subMapped = "N";
            break;
          default:
            subMapped = sub;
        }

        return subMapped;
      };

      $scope.filterByLine = function (line) {
        var existingSearch = "line:" + $scope.selectedLine;
        var newSearch = "line:" + line;

        if ($scope.selectedLine) {
          // if selected populated, that means there was a search before...remove that first 
          $scope.removeExistingSearchFromSearch(existingSearch);
        }

        if ($scope.selectedLine === line) {
          // if same thing was clicked again...already been remove from search...just reset vars
          $scope.selectedLine = null;
        } else {
          // this is a new search, add to search
          $scope.prepSearchForNewSearch();
          $scope.addNewSearchToSearch(newSearch);
          $scope.selectedLine = line;
        }

        $scope.resetSort();
      };

      $scope.filterByPosition = function (position) {
        var existingSearch = "position:" + $scope.selectedPosition;
        var newSearch = "position:" + position;

        if ($scope.selectedPosition) {
          // if selected populated, that means there was a search before...remove that first 
          $scope.removeExistingSearchFromSearch(existingSearch);
        }

        if ($scope.selectedPosition === position) {
          // if same thing was clicked again...already been remove from search...just reset vars
          $scope.selectedPosition = null;
        } else {
          // this is a new search, add to search
          $scope.prepSearchForNewSearch();
          $scope.addNewSearchToSearch(newSearch);
          $scope.selectedPosition = position;
        }

        $scope.resetSort();
      };

      $scope.resetSort = function (newSearch) {
        //$scope.sortDescFirst('p');
      };

      $scope.addNewSearchToSearch = function (newSearch) {
        $scope.searchText = $scope.searchText + newSearch;
      };

      $scope.removeExistingSearchFromSearch = function (existingSearch) {
        $scope.searchText = $scope.searchText.replace(", " + existingSearch, "");
        $scope.searchText = $scope.searchText.replace(existingSearch + ", ", "");
        $scope.searchText = $scope.searchText.replace(existingSearch, "");
      };

      $scope.prepSearchForNewSearch = function () {
        if ($scope.searchText) {
          $scope.searchText = $scope.searchText + ", ";
        } else {
          $scope.searchText = "";
        }
      };

      $scope.sortAscFirst = function (column) {
        if ($scope.sortOn === column) {
          $scope.sortDirection = !$scope.sortDirection;
        } else {
          $scope.sortOn = column;
          $scope.sortDirection = false;
        }
      };

      $scope.sortDescFirst = function (column) {
        if ($scope.sortOn === column) {
          $scope.sortDirection = !$scope.sortDirection;
        } else {
          $scope.sortOn = column;
          $scope.sortDirection = true;
        }
      };

      $scope.removeSearch = function () {
        $scope.searchText = null;
        $scope.selectedTeam = null;
        $scope.selectedPosition = null;
        $scope.selectedLine = null;
        $scope.selectedSub = null;
      }

      $scope.activate = function () {
        $timeout(function () {
          $scope.sortDescFirst('p');
          $scope.filterBySub("Without");
        }, 0);  // using timeout so it fires when done rendering
      };

      $scope.teams = [
        "Bill Brown",
      "Hunt's Ace",
      "LAB/PSI",
      "Zas Ent",
      "DPKZ",
      "Villanova",
      "Glover",
      "D&G"
      ];

      $scope.positions = [
        "F",
        "D",
        "G"
      ];

      $scope.subs = [
        "With",
        "Without",
      ];

      $scope.lines = [
        "1",
        "2",
        "3",
      ];

      $scope.playerStats = [
  {
    pid: 631,
    stidpf: 312,
    sid: 54,
    player: "Dave Hamilton",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 16,
    a: 8,
    p: 24,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 593,
    stidpf: 308,
    sid: 54,
    player: "Dan Hunt",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 9,
    g: 10,
    a: 11,
    p: 21,
    pim: 0,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 609,
    stidpf: 310,
    sid: 54,
    player: "Matt Sharkey",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 10,
    a: 7,
    p: 17,
    pim: 0,
    ppg: 1,
    shg: 1,
    gwg: 0
  },
  {
    pid: 119,
    stidpf: 312,
    sid: 54,
    player: "Bill Marken",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 9,
    g: 1,
    a: 13,
    p: 14,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 237,
    stidpf: 311,
    sid: 54,
    player: "Phil Sexton",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 9,
    g: 4,
    a: 10,
    p: 14,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 618,
    stidpf: 308,
    sid: 54,
    player: "Mike Gambino",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 7,
    g: 5,
    a: 8,
    p: 13,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 660,
    stidpf: 309,
    sid: 54,
    player: "Pete Mazzoni",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 9,
    g: 6,
    a: 7,
    p: 13,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 765,
    stidpf: 309,
    sid: 54,
    player: "Chris Niemiec",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 6,
    a: 7,
    p: 13,
    pim: 0,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 635,
    stidpf: 310,
    sid: 54,
    player: "Justin Osman",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 6,
    a: 6,
    p: 12,
    pim: 6,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 629,
    stidpf: 311,
    sid: 54,
    player: "Joel Massa",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 8,
    g: 6,
    a: 6,
    p: 12,
    pim: 6,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 677,
    stidpf: 308,
    sid: 54,
    player: "Pat Gilson",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 7,
    g: 4,
    a: 7,
    p: 11,
    pim: 0,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 656,
    stidpf: 312,
    sid: 54,
    player: "Glenn Heath",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 3,
    a: 7,
    p: 10,
    pim: 0,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 612,
    stidpf: 309,
    sid: 54,
    player: "Greg Panaretos",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 3,
    a: 7,
    p: 10,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 589,
    stidpf: 315,
    sid: 54,
    player: "Sean Rush",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 8,
    g: 4,
    a: 6,
    p: 10,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 36,
    stidpf: 312,
    sid: 54,
    player: "Mick Hunt",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 10,
    g: 2,
    a: 8,
    p: 10,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 52,
    stidpf: 314,
    sid: 54,
    player: "Dave McCallum",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 3,
    a: 7,
    p: 10,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 44,
    stidpf: 312,
    sid: 54,
    player: "John Weak",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 7,
    a: 2,
    p: 9,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 3,
    stidpf: 315,
    sid: 54,
    player: "Wally Pivetta Jr",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 2,
    a: 7,
    p: 9,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 4,
    stidpf: 314,
    sid: 54,
    player: "Doug Smith",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 10,
    g: 2,
    a: 7,
    p: 9,
    pim: 0,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 85,
    stidpf: 315,
    sid: 54,
    player: "Dan Fredendall",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 7,
    g: 3,
    a: 6,
    p: 9,
    pim: 3,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 594,
    stidpf: 310,
    sid: 54,
    player: "BJ Eglinton",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 10,
    g: 0,
    a: 9,
    p: 9,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 584,
    stidpf: 310,
    sid: 54,
    player: "Paul Seychel",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 10,
    g: 5,
    a: 4,
    p: 9,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 625,
    stidpf: 315,
    sid: 54,
    player: "Bill Dietz",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 4,
    a: 5,
    p: 9,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 235,
    stidpf: 312,
    sid: 54,
    player: "Jim Weak",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 11,
    g: 1,
    a: 8,
    p: 9,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 204,
    stidpf: 310,
    sid: 54,
    player: "Tony Zaschak",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 9,
    g: 1,
    a: 8,
    p: 9,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 686,
    stidpf: 315,
    sid: 54,
    player: "Kris Medico",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 5,
    a: 4,
    p: 9,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 734,
    stidpf: 314,
    sid: 54,
    player: "Nathan Jakubowski",
    team: "Villanova Construction",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 10,
    g: 4,
    a: 5,
    p: 9,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 710,
    stidpf: 313,
    sid: 54,
    player: "Howard Schoenfeldt",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 8,
    g: 5,
    a: 3,
    p: 8,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 731,
    stidpf: 309,
    sid: 54,
    player: "Nick Niemiec",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 2,
    a: 6,
    p: 8,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 624,
    stidpf: 313,
    sid: 54,
    player: "Mike Davis",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 9,
    g: 4,
    a: 4,
    p: 8,
    pim: 12,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 180,
    stidpf: 315,
    sid: 54,
    player: "Steve Sobczak",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 10,
    g: 6,
    a: 1,
    p: 7,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 173,
    stidpf: 314,
    sid: 54,
    player: "Doug Walters",
    team: "Villanova Construction",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 11,
    g: 5,
    a: 2,
    p: 7,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 38,
    stidpf: 312,
    sid: 54,
    player: "Ken Hunt Jr",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 11,
    g: 6,
    a: 1,
    p: 7,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 53,
    stidpf: 314,
    sid: 54,
    player: "Andy McCallum",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 9,
    g: 3,
    a: 3,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 108,
    stidpf: 315,
    sid: 54,
    player: "Al Szczepanik",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 10,
    g: 0,
    a: 6,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 70,
    stidpf: 308,
    sid: 54,
    player: "Rick Hamlin",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 10,
    g: 3,
    a: 3,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 206,
    stidpf: 308,
    sid: 54,
    player: "Mark Brosky",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 10,
    g: 2,
    a: 4,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 575,
    stidpf: 310,
    sid: 54,
    player: "Steve Jarzembowski",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 4,
    a: 2,
    p: 6,
    pim: 2,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 585,
    stidpf: 311,
    sid: 54,
    player: "Scott Irvine",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 7,
    g: 2,
    a: 4,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 605,
    stidpf: 314,
    sid: 54,
    player: "Tony Soave",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 4,
    a: 2,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 644,
    stidpf: 314,
    sid: 54,
    player: "Doug Wagel",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 2,
    a: 4,
    p: 6,
    pim: 3,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 653,
    stidpf: 313,
    sid: 54,
    player: "Doug Scott",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 4,
    a: 2,
    p: 6,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 655,
    stidpf: 308,
    sid: 54,
    player: "Dan Cretu",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 2,
    g: 1,
    a: 5,
    p: 6,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 690,
    stidpf: 310,
    sid: 54,
    player: "Eric Hudzinski",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 3,
    a: 2,
    p: 5,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 626,
    stidpf: 315,
    sid: 54,
    player: "John Labadie",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 9,
    g: 2,
    a: 3,
    p: 5,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 576,
    stidpf: 308,
    sid: 54,
    player: "Richard Maiz",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 3,
    a: 2,
    p: 5,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 185,
    stidpf: 313,
    sid: 54,
    player: "Scott Green",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 2,
    a: 3,
    p: 5,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 123,
    stidpf: 311,
    sid: 54,
    player: "Randy Hope",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 9,
    g: 2,
    a: 3,
    p: 5,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 62,
    stidpf: 309,
    sid: 54,
    player: "Matt Kobliska",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 9,
    g: 3,
    a: 2,
    p: 5,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 74,
    stidpf: 310,
    sid: 54,
    player: "Scott Grace",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 9,
    g: 4,
    a: 1,
    p: 5,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 83,
    stidpf: 313,
    sid: 54,
    player: "Bill Tabor",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 10,
    g: 2,
    a: 3,
    p: 5,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 11,
    stidpf: 313,
    sid: 54,
    player: "Dennis Elenich Sr",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 3,
    a: 2,
    p: 5,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 6,
    stidpf: 315,
    sid: 54,
    player: "Kevin Carlsen",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 6,
    g: 1,
    a: 3,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 17,
    stidpf: 313,
    sid: 54,
    player: "Kevin Green",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 9,
    g: 1,
    a: 3,
    p: 4,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 43,
    stidpf: 312,
    sid: 54,
    player: "Ray Newer",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 2,
    a: 2,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 59,
    stidpf: 312,
    sid: 54,
    player: "Rich Newer",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 1,
    a: 3,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 45,
    stidpf: 308,
    sid: 54,
    player: "Marc Brookman",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 8,
    g: 2,
    a: 2,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 105,
    stidpf: 311,
    sid: 54,
    player: "Al Jensen",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 9,
    g: 2,
    a: 2,
    p: 4,
    pim: 3,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 79,
    stidpf: 310,
    sid: 54,
    player: "Jim Hudzinski",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 0,
    a: 4,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 67,
    stidpf: 313,
    sid: 54,
    player: "Peter Howard",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 10,
    g: 1,
    a: 3,
    p: 4,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 233,
    stidpf: 309,
    sid: 54,
    player: "Carl Gerhard",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 10,
    g: 1,
    a: 3,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 573,
    stidpf: 312,
    sid: 54,
    player: "Rob Putman",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 0,
    a: 4,
    p: 4,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 617,
    stidpf: 310,
    sid: 54,
    player: "Mark Dowd",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 10,
    g: 3,
    a: 1,
    p: 4,
    pim: 3,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 590,
    stidpf: 311,
    sid: 54,
    player: "Jim Gibboney",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 8,
    g: 2,
    a: 2,
    p: 4,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 577,
    stidpf: 313,
    sid: 54,
    player: "Dave Elenich",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 11,
    g: 0,
    a: 4,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 718,
    stidpf: 311,
    sid: 54,
    player: "Dan Waligora",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 6,
    g: 2,
    a: 2,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 658,
    stidpf: 308,
    sid: 54,
    player: "Phil Rea",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 7,
    g: 3,
    a: 1,
    p: 4,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 762,
    stidpf: 309,
    sid: 54,
    player: "Scott Ranta",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 10,
    g: 1,
    a: 3,
    p: 4,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 659,
    stidpf: 314,
    sid: 54,
    player: "Pete Soave",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 652,
    stidpf: 308,
    sid: 54,
    player: "Jim Iavasile",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 1,
    a: 2,
    p: 3,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 638,
    stidpf: 313,
    sid: 54,
    player: "Andrew MacEachern",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 11,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 639,
    stidpf: 315,
    sid: 54,
    player: "Ken Masiarczyk",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 9,
    g: 0,
    a: 3,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 708,
    stidpf: 308,
    sid: 54,
    player: "Vince DeMassa",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 3,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 739,
    stidpf: 308,
    sid: 54,
    player: "Darren Mills",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 3,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 700,
    stidpf: 313,
    sid: 54,
    player: "BJ Teahan",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 3,
    g: 0,
    a: 3,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 629,
    stidpf: 315,
    sid: 54,
    player: "Joel Massa",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 478,
    stidpf: 310,
    sid: 54,
    player: "Bob Krauss",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 0,
    a: 3,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 162,
    stidpf: 308,
    sid: 54,
    player: "Steve Gilson",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 10,
    g: 0,
    a: 3,
    p: 3,
    pim: 7,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 164,
    stidpf: 312,
    sid: 54,
    player: "Brian McDonald",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 8,
    g: 0,
    a: 3,
    p: 3,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 77,
    stidpf: 314,
    sid: 54,
    player: "John Walters",
    team: "Villanova Construction",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 11,
    g: 0,
    a: 3,
    p: 3,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 100,
    stidpf: 313,
    sid: 54,
    player: "Brett Green",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 6,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 110,
    stidpf: 309,
    sid: 54,
    player: "Tom Kwiatkowski",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 2,
    a: 1,
    p: 3,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 96,
    stidpf: 312,
    sid: 54,
    player: "Bob Tenaglia",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 10,
    g: 2,
    a: 1,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 98,
    stidpf: 310,
    sid: 54,
    player: "Larry Jaynes",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 0,
    a: 3,
    p: 3,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 60,
    stidpf: 313,
    sid: 54,
    player: "Steve Crandall",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 11,
    g: 0,
    a: 3,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 61,
    stidpf: 312,
    sid: 54,
    player: "Lou Barrett",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 9,
    g: 0,
    a: 3,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 51,
    stidpf: 315,
    sid: 54,
    player: "Ron Tetrault",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 9,
    g: 0,
    a: 3,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 19,
    stidpf: 312,
    sid: 54,
    player: "Bruce Henderson",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 11,
    g: 0,
    a: 3,
    p: 3,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 33,
    stidpf: 315,
    sid: 54,
    player: "Todd Keller",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 10,
    g: 1,
    a: 2,
    p: 3,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 15,
    stidpf: 313,
    sid: 54,
    player: "Joseph Tseng",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 20,
    stidpf: 308,
    sid: 54,
    player: "Robert Smythe",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 1,
    gp: 4,
    g: 1,
    a: 1,
    p: 2,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 105,
    stidpf: 308,
    sid: 54,
    player: "Al Jensen",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 71,
    stidpf: 315,
    sid: 54,
    player: "Mike Hermann",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 1,
    a: 1,
    p: 2,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 64,
    stidpf: 309,
    sid: 54,
    player: "Mark Ranta",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 0,
    a: 2,
    p: 2,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 175,
    stidpf: 313,
    sid: 54,
    player: "Mike Sinclair",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 2,
    a: 0,
    p: 2,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 114,
    stidpf: 314,
    sid: 54,
    player: "Kevin Mason",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 10,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 575,
    stidpf: 308,
    sid: 54,
    player: "Steve Jarzembowski",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 2,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 184,
    stidpf: 314,
    sid: 54,
    player: "Keith Gudeman",
    team: "Villanova Construction",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 9,
    g: 1,
    a: 1,
    p: 2,
    pim: 7,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 621,
    stidpf: 308,
    sid: 54,
    player: "Joseph Iannotti",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 8,
    g: 0,
    a: 2,
    p: 2,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 581,
    stidpf: 313,
    sid: 54,
    player: "Kyle Krupsky",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 3,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 583,
    stidpf: 314,
    sid: 54,
    player: "Ed Lutz",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 11,
    g: 2,
    a: 0,
    p: 2,
    pim: 0,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 608,
    stidpf: 310,
    sid: 54,
    player: "Jeff Hickson",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 11,
    g: 1,
    a: 1,
    p: 2,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 594,
    stidpf: 315,
    sid: 54,
    player: "BJ Eglinton",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 2,
    a: 0,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 684,
    stidpf: 312,
    sid: 54,
    player: "Matt Grant",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 670,
    stidpf: 309,
    sid: 54,
    player: "Corey Swider",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 2,
    g: 1,
    a: 1,
    p: 2,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 680,
    stidpf: 308,
    sid: 54,
    player: "Dominic Catanzarite",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 2,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 680,
    stidpf: 314,
    sid: 54,
    player: "Dominic Catanzarite",
    team: "Villanova Construction",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 1,
    a: 1,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 716,
    stidpf: 308,
    sid: 54,
    player: "Jason Dawes",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 2,
    g: 1,
    a: 1,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 642,
    stidpf: 308,
    sid: 54,
    player: "Jeff Featherston",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 2,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 644,
    stidpf: 309,
    sid: 54,
    player: "Doug Wagel",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 2,
    g: 1,
    a: 1,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 662,
    stidpf: 308,
    sid: 54,
    player: "Matt Spease",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 4,
    g: 1,
    a: 1,
    p: 2,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 634,
    stidpf: 315,
    sid: 54,
    player: "Tony Brosky",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 10,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 645,
    stidpf: 311,
    sid: 54,
    player: "Kevin Hall",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 645,
    stidpf: 313,
    sid: 54,
    player: "Kevin Hall",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 646,
    stidpf: 308,
    sid: 54,
    player: "Jerry Brown",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 727,
    stidpf: 313,
    sid: 54,
    player: "Brad Larsh",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 710,
    stidpf: 308,
    sid: 54,
    player: "Howard Schoenfeldt",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 3,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 743,
    stidpf: 311,
    sid: 54,
    player: "Tony Hall",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 678,
    stidpf: 308,
    sid: 54,
    player: "Mark Felker",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 10,
    g: 0,
    a: 1,
    p: 1,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 766,
    stidpf: 310,
    sid: 54,
    player: "Jeff Lapointe",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 1,
    a: 0,
    p: 1,
    pim: 2,
    ppg: 1,
    shg: 0,
    gwg: 0
  },
  {
    pid: 664,
    stidpf: 310,
    sid: 54,
    player: "Randy Roulier",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 10,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 757,
    stidpf: 311,
    sid: 54,
    player: "Gary Zielke",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 2,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 590,
    stidpf: 308,
    sid: 54,
    player: "Jim Gibboney",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 578,
    stidpf: 315,
    sid: 54,
    player: "Dan Covert",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 586,
    stidpf: 311,
    sid: 54,
    player: "Gordon Stefanick",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 3,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 616,
    stidpf: 309,
    sid: 54,
    player: "Joe Giroux",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 11,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 201,
    stidpf: 309,
    sid: 54,
    player: "Gary Dowd",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 201,
    stidpf: 314,
    sid: 54,
    player: "Gary Dowd",
    team: "Villanova Construction",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 1,
    a: 0,
    p: 1,
    pim: 8,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 118,
    stidpf: 309,
    sid: 54,
    player: "Joe Niemiec",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 11,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 237,
    stidpf: 313,
    sid: 54,
    player: "Phil Sexton",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 3,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 363,
    stidpf: 311,
    sid: 54,
    player: "Dave Felker",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 162,
    stidpf: 310,
    sid: 54,
    player: "Steve Gilson",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "D",
    line: 3,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 67,
    stidpf: 311,
    sid: 54,
    player: "Peter Howard",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 63,
    stidpf: 314,
    sid: 54,
    player: "Kevin Fitzpatrick",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 106,
    stidpf: 312,
    sid: 54,
    player: "Gary Vorhes",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 106,
    stidpf: 313,
    sid: 54,
    player: "Gary Vorhes",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 7,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 99,
    stidpf: 309,
    sid: 54,
    player: "Tom Fedrigo",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 11,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 82,
    stidpf: 315,
    sid: 54,
    player: "John C Strauch Jr",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 9,
    g: 1,
    a: 0,
    p: 1,
    pim: 5,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 92,
    stidpf: 309,
    sid: 54,
    player: "Gary Cutsy",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 10,
    g: 0,
    a: 1,
    p: 1,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 87,
    stidpf: 311,
    sid: 54,
    player: "Norm Smythe",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 6,
    g: 1,
    a: 0,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 23,
    stidpf: 314,
    sid: 54,
    player: "Ken Jakubowski",
    team: "Villanova Construction",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 11,
    g: 0,
    a: 1,
    p: 1,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 25,
    stidpf: 308,
    sid: 54,
    player: "Dennis Queener",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 35,
    stidpf: 311,
    sid: 54,
    player: "Don Trybus",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 8,
    g: 0,
    a: 1,
    p: 1,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 55,
    stidpf: 308,
    sid: 54,
    player: "Bob Toaso",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 8,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 7,
    stidpf: 314,
    sid: 54,
    player: "Dennis Kahle",
    team: "Villanova Construction",
    sub: "Y",
    pos: "D",
    line: 3,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 42,
    stidpf: 314,
    sid: 54,
    player: "Joe Grezlik",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 1,
    p: 1,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 40,
    stidpf: 309,
    sid: 54,
    player: "Mike Lysaght",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "D",
    line: 2,
    gp: 10,
    g: 0,
    a: 1,
    p: 1,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 42,
    stidpf: 308,
    sid: 54,
    player: "Joe Grezlik",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 42,
    stidpf: 311,
    sid: 54,
    player: "Joe Grezlik",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 49,
    stidpf: 312,
    sid: 54,
    player: "John Camillo",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 7,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 55,
    stidpf: 311,
    sid: 54,
    player: "Bob Toaso",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 35,
    stidpf: 314,
    sid: 54,
    player: "Don Trybus",
    team: "Villanova Construction",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 7,
    stidpf: 311,
    sid: 54,
    player: "Dennis Kahle",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 9,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 25,
    stidpf: 311,
    sid: 54,
    player: "Dennis Queener",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 25,
    stidpf: 312,
    sid: 54,
    player: "Dennis Queener",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 29,
    stidpf: 311,
    sid: 54,
    player: "Jack Pellosma Jr",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 9,
    g: 0,
    a: 0,
    p: 0,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 31,
    stidpf: 313,
    sid: 54,
    player: "Larry Fedrigo",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 32,
    stidpf: 311,
    sid: 54,
    player: "Steve Galvan",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 8,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 87,
    stidpf: 314,
    sid: 54,
    player: "Norm Smythe",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 85,
    stidpf: 314,
    sid: 54,
    player: "Dan Fredendall",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 111,
    stidpf: 309,
    sid: 54,
    player: "Matt Barrett",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 11,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 106,
    stidpf: 310,
    sid: 54,
    player: "Gary Vorhes",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 73,
    stidpf: 314,
    sid: 54,
    player: "Ed Maksimowicz",
    team: "Villanova Construction",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 10,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 81,
    stidpf: 311,
    sid: 54,
    player: "Ron Gabon",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "G",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 63,
    stidpf: 312,
    sid: 54,
    player: "Kevin Fitzpatrick",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 71,
    stidpf: 308,
    sid: 54,
    player: "Mike Hermann",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 71,
    stidpf: 311,
    sid: 54,
    player: "Mike Hermann",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 71,
    stidpf: 312,
    sid: 54,
    player: "Mike Hermann",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 71,
    stidpf: 313,
    sid: 54,
    player: "Mike Hermann",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 165,
    stidpf: 315,
    sid: 54,
    player: "Dan Persha",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "N",
    pos: "F",
    line: 2,
    gp: 6,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 177,
    stidpf: 310,
    sid: 54,
    player: "Steve Roth",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 11,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 178,
    stidpf: 311,
    sid: 54,
    player: "Ken Grant",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 8,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 116,
    stidpf: 311,
    sid: 54,
    player: "Ken May",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "D",
    line: 1,
    gp: 4,
    g: 0,
    a: 0,
    p: 0,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 120,
    stidpf: 312,
    sid: 54,
    player: "George Weiser",
    team: "Hunt's Ace Hardware",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 11,
    g: 0,
    a: 0,
    p: 0,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 120,
    stidpf: 313,
    sid: 54,
    player: "George Weiser",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 126,
    stidpf: 308,
    sid: 54,
    player: "Russ Baumann Sr",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 130,
    stidpf: 311,
    sid: 54,
    player: "Player Unknown",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 130,
    stidpf: 315,
    sid: 54,
    player: "Player Unknown",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 576,
    stidpf: 310,
    sid: 54,
    player: "Richard Maiz",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 2,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 202,
    stidpf: 314,
    sid: 54,
    player: "Chris Darnell",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 202,
    stidpf: 315,
    sid: 54,
    player: "Chris Darnell",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 617,
    stidpf: 309,
    sid: 54,
    player: "Mark Dowd",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 617,
    stidpf: 312,
    sid: 54,
    player: "Mark Dowd",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 619,
    stidpf: 313,
    sid: 54,
    player: "Brad Villa",
    team: "D&G Heating & Cooling",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 10,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 625,
    stidpf: 314,
    sid: 54,
    player: "Bill Dietz",
    team: "Villanova Construction",
    sub: "Y",
    pos: "D",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 586,
    stidpf: 313,
    sid: 54,
    player: "Gordon Stefanick",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 586,
    stidpf: 309,
    sid: 54,
    player: "Gordon Stefanick",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 584,
    stidpf: 308,
    sid: 54,
    player: "Paul Seychel",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 592,
    stidpf: 315,
    sid: 54,
    player: "Tom Covert",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 758,
    stidpf: 315,
    sid: 54,
    player: "Paul Fretter",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "D",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 678,
    stidpf: 312,
    sid: 54,
    player: "Mark Felker",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "G",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 676,
    stidpf: 312,
    sid: 54,
    player: "Mike Guider Jr",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "G",
    line: 1,
    gp: 2,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 682,
    stidpf: 311,
    sid: 54,
    player: "Scott Fassett",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 8,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 682,
    stidpf: 313,
    sid: 54,
    player: "Scott Fassett",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "G",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 684,
    stidpf: 310,
    sid: 54,
    player: "Matt Grant",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 686,
    stidpf: 311,
    sid: 54,
    player: "Kris Medico",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 688,
    stidpf: 309,
    sid: 54,
    player: "Lenny Domanke",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "G",
    line: 1,
    gp: 2,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 706,
    stidpf: 314,
    sid: 54,
    player: "Darrell Lupu",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 693,
    stidpf: 310,
    sid: 54,
    player: "Dennis Richardson",
    team: "Zaschak Enterprises",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 11,
    g: 0,
    a: 0,
    p: 0,
    pim: 4,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 748,
    stidpf: 314,
    sid: 54,
    player: "Mike Thompson",
    team: "Villanova Construction",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 749,
    stidpf: 314,
    sid: 54,
    player: "Jon Ameel",
    team: "Villanova Construction",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 11,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 751,
    stidpf: 308,
    sid: 54,
    player: "John Pittman",
    team: "Bill Brown Auto Clinic",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 752,
    stidpf: 313,
    sid: 54,
    player: "Erick Sprout",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 735,
    stidpf: 310,
    sid: 54,
    player: "Steve Cordon",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 737,
    stidpf: 309,
    sid: 54,
    player: "Brian Whetstone",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "N",
    pos: "G",
    line: 1,
    gp: 9,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 738,
    stidpf: 311,
    sid: 54,
    player: "Zachary Nienus",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 710,
    stidpf: 314,
    sid: 54,
    player: "Howard Schoenfeldt",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 716,
    stidpf: 309,
    sid: 54,
    player: "Jason Dawes",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 716,
    stidpf: 314,
    sid: 54,
    player: "Jason Dawes",
    team: "Villanova Construction",
    sub: "Y",
    pos: "F",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 646,
    stidpf: 310,
    sid: 54,
    player: "Jerry Brown",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 2,
    g: 0,
    a: 0,
    p: 0,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 646,
    stidpf: 313,
    sid: 54,
    player: "Jerry Brown",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 647,
    stidpf: 312,
    sid: 54,
    player: "Dave Antczak",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 647,
    stidpf: 313,
    sid: 54,
    player: "Dave Antczak",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "F",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 648,
    stidpf: 312,
    sid: 54,
    player: "Dave Adamczyk",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 650,
    stidpf: 312,
    sid: 54,
    player: "Chris Ciszewski",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "G",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 638,
    stidpf: 312,
    sid: 54,
    player: "Andrew MacEachern",
    team: "Hunt's Ace Hardware",
    sub: "Y",
    pos: "D",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 642,
    stidpf: 311,
    sid: 54,
    player: "Jeff Featherston",
    team: "Jeff Glover Realtors",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 663,
    stidpf: 308,
    sid: 54,
    player: "Gerry Folk",
    team: "Bill Brown Auto Clinic",
    sub: "N",
    pos: "D",
    line: 3,
    gp: 9,
    g: 0,
    a: 0,
    p: 0,
    pim: 2,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 663,
    stidpf: 309,
    sid: 54,
    player: "Gerry Folk",
    team: "DeBrincat Padgett Kobliska Zick",
    sub: "Y",
    pos: "D",
    line: 3,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 661,
    stidpf: 310,
    sid: 54,
    player: "Anthony Larson",
    team: "Zaschak Enterprises",
    sub: "Y",
    pos: "D",
    line: 1,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 659,
    stidpf: 315,
    sid: 54,
    player: "Pete Soave",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 644,
    stidpf: 313,
    sid: 54,
    player: "Doug Wagel",
    team: "D&G Heating & Cooling",
    sub: "Y",
    pos: "D",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 644,
    stidpf: 315,
    sid: 54,
    player: "Doug Wagel",
    team: "Liv. Auto Body/Phillips Service Ind",
    sub: "Y",
    pos: "F",
    line: 2,
    gp: 1,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  },
  {
    pid: 654,
    stidpf: 311,
    sid: 54,
    player: "Chris Garbacz",
    team: "Jeff Glover Realtors",
    sub: "N",
    pos: "F",
    line: 3,
    gp: 9,
    g: 0,
    a: 0,
    p: 0,
    pim: 0,
    ppg: 0,
    shg: 0,
    gwg: 0
  }
      ];

      $scope.activate();
    }
  ]
);