using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LO30.Data
{
  public class PlayerStatType
  {
    public PlayerStatType()
    {
    }

    public PlayerStatType(bool sub, string name)
    {
      //this.PlayerStatTypeId = pstid;  // generated by database
      this.Sub = sub;
      this.PlayerStatTypeName = name;

      Validate();
    }

    public PlayerStatType(int pstid, bool sub, string name)
    {
      this.PlayerStatTypeId = pstid;
      this.Sub = sub;
      this.PlayerStatTypeName = name;

      Validate();
    }

    [Key, Column(Order = 0)]
    public int PlayerStatTypeId { get; set; }

    [Index("PK2", 1, IsUnique = true)]
    public bool Sub { get; set; }

    [Required, MaxLength(25)]
    public string PlayerStatTypeName { get; set; }

    private void Validate()
    {
      var locationKey = string.Format("pstid: {0}, sub: {1}",
                            this.PlayerStatTypeId,
                            this.Sub);

      if (this.Sub == true && this.PlayerStatTypeName.ToLower().IndexOf("sub") == -1)
      {
        throw new ArgumentException("If Sub is true, PlayerStatTypeName must have the word sub in it for:" + locationKey, "PlayerStatTypeName");
      }
    }
  }
}