var ngModule = angular.module("ngScoreSheetModule", ['ngRoute', 'ngResource']);

ngModule.config(["$routeProvider", function ($routeProvider) {
  $routeProvider.when("/", {
    controller: "scoreSheetController",
    templateUrl: "/Templates/ScoreSheetAngular.html"
  });
  $routeProvider.otherwise({ redirectTo: "/" });
}]);

ngModule.factory("scoreSheetService", ["$resource", function ($resource) {

  var resource = $resource('/api/v1/scoreSheet');

  var postAction = function (model) {
    return resource.save({}, model);
  };

  return {
    postAction: postAction
  };
}]);

ngModule.controller('scoreSheetController', ['$scope', 'scoreSheetService', function ($scope, scoreSheetService) {
  $scope.data = {
    game: {},
    gameRosters: []
  }

  $scope.data.game = { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 };

  $scope.data.gameRosters = [
  { "GameRosterId": 315, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 20, "PlayerNumber": 9, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 316, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 4, "PlayerNumber": 9, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 317, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 652, "PlayerNumber": 8, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 318, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 23, "PlayerNumber": 6, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 319, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 593, "PlayerNumber": 7, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 320, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 52, "PlayerNumber": 21, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 321, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 618, "PlayerNumber": 10, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 322, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 53, "PlayerNumber": 11, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 323, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 658, "PlayerNumber": 6, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 324, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 42, "PlayerNumber": 27, "Position": "F", "Sub": true, "SubbingForPlayer": null, "SubbingForPlayerId": 73 },
 { "GameRosterId": 325, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 716, "PlayerNumber": 18, "Position": "D", "Sub": true, "SubbingForPlayer": null, "SubbingForPlayerId": 663 },
 { "GameRosterId": 326, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 77, "PlayerNumber": 3, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 327, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 70, "PlayerNumber": 22, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 328, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 114, "PlayerNumber": 15, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 329, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 206, "PlayerNumber": 20, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 330, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 173, "PlayerNumber": 19, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 331, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 162, "PlayerNumber": 3, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 332, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 184, "PlayerNumber": 7, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 333, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 55, "PlayerNumber": 2, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 334, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 201, "PlayerNumber": 10, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 335, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 662, "PlayerNumber": 17, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 336, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 2, "Player": null, "PlayerId": 583, "PlayerNumber": 17, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 337, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 45, "PlayerNumber": 14, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 338, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 605, "PlayerNumber": 22, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 339, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 576, "PlayerNumber": 12, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 340, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 644, "PlayerNumber": 23, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 341, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 621, "PlayerNumber": 4, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 342, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 3, "Player": null, "PlayerId": 659, "PlayerNumber": 12, "Position": "F", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 343, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 677, "PlayerNumber": 5, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 344, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": false, "Line": 1, "Player": null, "PlayerId": 734, "PlayerNumber": 2, "Position": "D", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 345, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 9, "HomeTeam": true, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 308, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 317, "TeamLongName": "Bill Brown Auto Clinic", "TeamShortName": "Bill Brown" }, "TeamId": 317 }, "SeasonTeamId": 308 }, "GameTeamId": 9, "Goalie": true, "Line": 1, "Player": null, "PlayerId": 678, "PlayerNumber": 30, "Position": "G", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null },
 { "GameRosterId": 346, "GameTeam": { "Game": { "GameDateTime": "\/Date(1410125400000-0400)\/", "GameId": 3200, "Location": "not set", "Playoff": false, "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54 }, "GameId": 3200, "GameTeamId": 10, "HomeTeam": false, "SeasonTeam": { "Season": { "EndDate": null, "IsCurrentSeason": true, "SeasonId": 54, "SeasonName": "2014 - 2015", "StartDate": null }, "SeasonId": 54, "SeasonTeamId": 314, "Team": { "Coach": null, "CoachId": null, "Sponsor": null, "SponsorId": null, "TeamId": 323, "TeamLongName": "Villanova Construction", "TeamShortName": "Villanova" }, "TeamId": 323 }, "SeasonTeamId": 314 }, "GameTeamId": 10, "Goalie": true, "Line": 1, "Player": null, "PlayerId": 749, "PlayerNumber": 1, "Position": "G", "Sub": false, "SubbingForPlayer": null, "SubbingForPlayerId": null }
  ];

}]);

